name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  WEBAPP_NAME: DotNetFrameworkActions.sln     # set this to your application's name
  WEBAPP_PACKAGE_PATH: 'published'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build:
    name: Build and deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        working-directory: src
    
    - name: Restore NuGet packages
      run: nuget restore ${{ env.WEBAPP_NAME }}
      working-directory: src

    - name: Build
      run: msbuild ${{ env.WEBAPP_NAME }} /p:Configuration=Release
      working-directory: src

    - name: Publish to folder
      run: msbuild ${{ env.WEBAPP_NAME }} /p:Configuration=Release /p:DeployOnBuild=true /t:WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=${{ env.WEBAPP_PACKAGE_PATH }} /p:PackageAsSingleFile=false
      working-directory: src

    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        working-directory: src
        name: webapp
        path: ${{ env.WEBAPP_PACKAGE_PATH }}